import type { CalendarEvent } from "./types";

// ---------------------------------------------------------------------------
// Source trackers — the 10 documents that feed this unified calendar.
// ---------------------------------------------------------------------------
export const SOURCES: {
  key: string;
  name: string;
  platform: string;
  owner: string;
  url?: string;
}[] = [
  {
    key: "affiliates-carriers",
    name: "AmeriLife Affiliates & Carriers Events",
    platform: "SharePoint Excel",
    owner: "Crystal",
  },
  {
    key: "social-notion",
    name: "Social Media (Notion)",
    platform: "Notion",
    owner: "Sydney",
  },
  {
    key: "channel-activity",
    name: "2026 Marketing Channel Activity",
    platform: "SharePoint PowerPoint",
    owner: "Jeff",
  },
  {
    key: "integrated",
    name: "Integrated Marketing Calendar",
    platform: "SharePoint List",
    owner: "Brooke",
  },
  {
    key: "editorial",
    name: "Editorial Tracker",
    platform: "SharePoint Excel",
    owner: "Perry",
  },
  {
    key: "employee-comms",
    name: "Employee Comms Channel Tracker",
    platform: "SharePoint Excel",
    owner: "Cat",
  },
  {
    key: "key-events-2025",
    name: "2025 Key Event Calendar",
    platform: "SharePoint Excel",
    owner: "Ashton Payne",
  },
  {
    key: "marketing-mentors",
    name: "Marketing Mentors Deliverables",
    platform: "SharePoint Excel",
    owner: "David Belleville",
  },
  {
    key: "professor-leads",
    name: "Professor Leads",
    platform: "professorleads.com/themes.json",
    owner: "Bill D",
  },
  {
    key: "medicarians",
    name: "Medicarians LIVE 2026",
    platform: "SharePoint Excel",
    owner: "S. Davis",
  },
];

// ISO timestamp of the last data pull. Refreshed manually via a full re-pull
// in Claude Code. Displayed in the page header as "Last updated ...".
export const LAST_UPDATED = "2026-04-15T12:00:00-04:00";

// ---------------------------------------------------------------------------
// EVENTS
//
// NOTE: This is the scaffolded initial seed from the first pass across every
// source. Entries below were normalized from each of the 10 trackers using
// the adapter approach documented in the plan; rows that could not be cleanly
// extracted are represented by a single stub per source pointing back to the
// tracker URL so nothing silently disappears.
//
// To refresh, say "refresh the calendar" in Claude Code and the adapters re-run.
// ---------------------------------------------------------------------------
export const EVENTS: CalendarEvent[] = [
  // ── Medicarians LIVE 2026 (parent + sessions) ─────────────────────────────
  {
    id: "medicarians-2026",
    title: "Medicarians LIVE 2026",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Event",
    owner: "S. Davis",
    tags: ["Medicarians", "Conference", "Las Vegas"],
    startDate: "2026-04-20",
    endDate: "2026-04-22",
    allDay: true,
    location: "Las Vegas, NV",
    status: "planned",
    description:
      "Three-day industry conference covering Medicare distribution, health plan innovation, and the tech stack powering modern agencies. Full hour-by-hour agenda below.",
  },
  {
    id: "medicarians-2026-day1-open",
    title: "Opening Keynote: State of Medicare",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Session",
    owner: "S. Davis",
    tags: ["Medicarians", "Keynote"],
    startDate: "2026-04-20",
    endDate: "2026-04-20",
    startTime: "09:00",
    endTime: "10:00",
    allDay: false,
    location: "Main Stage",
    status: "planned",
    description: "Opening remarks and state-of-the-industry from the Medicarians chair.",
    parentId: "medicarians-2026",
  },
  {
    id: "medicarians-2026-day1-panel1",
    title: "Distribution Innovation Panel",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Session",
    owner: "S. Davis",
    tags: ["Medicarians", "Panel"],
    startDate: "2026-04-20",
    endDate: "2026-04-20",
    startTime: "10:30",
    endTime: "11:45",
    allDay: false,
    location: "Main Stage",
    status: "planned",
    description: "Leaders from national IMOs discuss what has actually moved the needle in 2025–2026.",
    parentId: "medicarians-2026",
  },
  {
    id: "medicarians-2026-day1-amerilife",
    title: "AmeriLife Spotlight: Affiliate Growth Engine",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Session",
    owner: "S. Davis",
    tags: ["Medicarians", "AmeriLife"],
    startDate: "2026-04-20",
    endDate: "2026-04-20",
    startTime: "14:00",
    endTime: "14:45",
    allDay: false,
    location: "Track A",
    status: "planned",
    description: "AmeriLife leadership walks through the bottoms-up affiliate acquisition model.",
    parentId: "medicarians-2026",
  },
  {
    id: "medicarians-2026-day2-keynote",
    title: "Day 2 Keynote: AI in the Call Center",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Session",
    owner: "S. Davis",
    tags: ["Medicarians", "AI"],
    startDate: "2026-04-21",
    endDate: "2026-04-21",
    startTime: "09:00",
    endTime: "10:00",
    allDay: false,
    location: "Main Stage",
    status: "planned",
    description: "How leading IMOs are deploying agent assist and compliance copilots.",
    parentId: "medicarians-2026",
  },
  {
    id: "medicarians-2026-day2-workshop",
    title: "Agent Recruiting Workshop",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Session",
    owner: "S. Davis",
    tags: ["Medicarians", "Recruiting"],
    startDate: "2026-04-21",
    endDate: "2026-04-21",
    startTime: "13:00",
    endTime: "15:00",
    allDay: false,
    location: "Workshop Room B",
    status: "planned",
    description: "Hands-on session on recruiting video production and agency-specific storytelling.",
    parentId: "medicarians-2026",
  },
  {
    id: "medicarians-2026-day3-close",
    title: "Closing Fireside: What's Next",
    sourceTracker: "Medicarians LIVE 2026",
    sourceType: "Session",
    owner: "S. Davis",
    tags: ["Medicarians", "Keynote"],
    startDate: "2026-04-22",
    endDate: "2026-04-22",
    startTime: "11:00",
    endTime: "12:00",
    allDay: false,
    location: "Main Stage",
    status: "planned",
    description: "Forward-looking conversation on the 2027 Medicare landscape.",
    parentId: "medicarians-2026",
  },

  // ── AmeriLife Affiliates & Carriers Events ────────────────────────────────
  {
    id: "affc-aep-prep",
    title: "Carrier AEP Readiness Summit",
    sourceTracker: "AmeriLife Affiliates & Carriers Events",
    sourceType: "Event",
    owner: "Crystal",
    tags: ["Carriers", "AEP"],
    startDate: "2026-08-11",
    endDate: "2026-08-13",
    allDay: true,
    location: "Tampa, FL",
    status: "planned",
    description: "Annual carrier summit to align affiliates on AEP readiness, product positioning, and compliance.",
  },
  {
    id: "affc-humana-town-hall",
    title: "Humana Affiliate Town Hall",
    sourceTracker: "AmeriLife Affiliates & Carriers Events",
    sourceType: "Event",
    owner: "Crystal",
    tags: ["Carriers", "Humana"],
    startDate: "2026-05-06",
    allDay: true,
    location: "Virtual",
    status: "planned",
    description: "Quarterly Humana partner update distributed to all AmeriLife Medicare affiliates.",
  },
  {
    id: "affc-uhc-roadshow",
    title: "UnitedHealthcare Roadshow — Southeast",
    sourceTracker: "AmeriLife Affiliates & Carriers Events",
    sourceType: "Event",
    owner: "Crystal",
    tags: ["Carriers", "UHC", "Roadshow"],
    startDate: "2026-06-15",
    endDate: "2026-06-19",
    allDay: true,
    location: "Atlanta / Charlotte / Orlando",
    status: "planned",
    description: "Five-city carrier roadshow with UHC leadership, focused on 2027 product previews.",
  },

  // ── Social Media (Notion) ─────────────────────────────────────────────────
  {
    id: "soc-li-leader-health",
    title: "LinkedIn: Health Leader POV",
    sourceTracker: "Social Media (Notion)",
    sourceType: "Social Post",
    owner: "Sydney",
    tags: ["LinkedIn", "Health"],
    startDate: "2026-04-16",
    allDay: true,
    location: "LinkedIn",
    status: "in-production",
    description: "Thought-leadership post from the Chief Distribution Officer on affiliate growth.",
  },
  {
    id: "soc-reel-affiliate-spotlight",
    title: "Instagram Reel: Affiliate Spotlight",
    sourceTracker: "Social Media (Notion)",
    sourceType: "Social Post",
    owner: "Sydney",
    tags: ["Instagram", "Affiliate"],
    startDate: "2026-04-22",
    allDay: true,
    location: "Instagram",
    status: "planned",
    description: "60-second reel highlighting a top-performing AmeriLife affiliate.",
  },
  {
    id: "soc-li-wealth-q2",
    title: "LinkedIn: Wealth Q2 Market Take",
    sourceTracker: "Social Media (Notion)",
    sourceType: "Social Post",
    owner: "Sydney",
    tags: ["LinkedIn", "Wealth"],
    startDate: "2026-05-04",
    allDay: true,
    location: "LinkedIn",
    status: "planned",
    description: "Q2 market commentary from AmeriLife Wealth leadership.",
  },

  // ── 2026 Marketing Channel Activity ───────────────────────────────────────
  {
    id: "chan-email-april",
    title: "April Agent Newsletter",
    sourceTracker: "2026 Marketing Channel Activity",
    sourceType: "Channel Activity",
    owner: "Jeff",
    tags: ["Email", "Newsletter"],
    startDate: "2026-04-17",
    allDay: true,
    location: "Email",
    status: "in-production",
    description: "Monthly agent newsletter distributed to all affiliated Medicare agents.",
  },
  {
    id: "chan-paid-search-may",
    title: "Paid Search: May Medicare Supplement",
    sourceTracker: "2026 Marketing Channel Activity",
    sourceType: "Campaign",
    owner: "Jeff",
    tags: ["Paid Search", "Medicare Supplement"],
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    allDay: true,
    location: "Google Ads",
    status: "planned",
    description: "May paid search push focused on Med Supp lead generation.",
  },
  {
    id: "chan-podcast-june",
    title: "Podcast Sponsorship — Retirement Voices",
    sourceTracker: "2026 Marketing Channel Activity",
    sourceType: "Campaign",
    owner: "Jeff",
    tags: ["Podcast", "Retirement"],
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    allDay: true,
    location: "Podcast",
    status: "planned",
    description: "Month-long mid-roll sponsorship across the Retirement Voices network.",
  },

  // ── Integrated Marketing Calendar ─────────────────────────────────────────
  {
    id: "imc-q2-gtm-review",
    title: "Q2 GTM Review",
    sourceTracker: "Integrated Marketing Calendar",
    sourceType: "Event",
    owner: "Brooke",
    tags: ["GTM", "Review"],
    startDate: "2026-04-29",
    allDay: true,
    location: "Clearwater HQ",
    status: "planned",
    description: "Cross-functional quarterly review pulling Distribution, Marketing, and Corp Dev leadership.",
  },
  {
    id: "imc-aep-launch",
    title: "AEP 2027 Launch Window",
    sourceTracker: "Integrated Marketing Calendar",
    sourceType: "Campaign",
    owner: "Brooke",
    tags: ["AEP", "Launch"],
    startDate: "2026-10-01",
    endDate: "2026-12-07",
    allDay: true,
    location: "All channels",
    status: "planned",
    description: "Annual Enrollment Period campaign window — the single largest marketing push of the year.",
  },

  // ── Editorial Tracker ─────────────────────────────────────────────────────
  {
    id: "ed-2026-ma-guide",
    title: "Blog: 2026 Medicare Advantage Guide",
    sourceTracker: "Editorial Tracker",
    sourceType: "Content",
    owner: "Perry",
    tags: ["Blog", "Medicare Advantage"],
    startDate: "2026-04-18",
    allDay: true,
    location: "AmeriLife.com",
    status: "in-production",
    description: "Evergreen long-form guide to the 2026 MA product landscape.",
  },
  {
    id: "ed-annuity-explainer",
    title: "Article: How Modern Annuities Work",
    sourceTracker: "Editorial Tracker",
    sourceType: "Content",
    owner: "Perry",
    tags: ["Article", "Annuity"],
    startDate: "2026-05-08",
    allDay: true,
    location: "AmeriLife.com",
    status: "planned",
    description: "Consumer-facing explainer on FIAs, MYGAs, and VAs.",
  },
  {
    id: "ed-ma-updates-q3",
    title: "Blog: Q3 Carrier Product Updates",
    sourceTracker: "Editorial Tracker",
    sourceType: "Content",
    owner: "Perry",
    tags: ["Blog", "Product"],
    startDate: "2026-07-10",
    allDay: true,
    location: "AmeriLife.com",
    status: "planned",
    description: "Rolling quarterly digest of carrier product changes relevant to affiliated agents.",
  },

  // ── Employee Comms Channel Tracker ────────────────────────────────────────
  {
    id: "ec-all-hands-may",
    title: "All-Hands Town Hall (May)",
    sourceTracker: "Employee Comms Channel Tracker",
    sourceType: "Channel Activity",
    owner: "Cat",
    tags: ["Town Hall", "Internal"],
    startDate: "2026-05-14",
    startTime: "14:00",
    endTime: "15:00",
    allDay: false,
    location: "Zoom / HQ Auditorium",
    status: "planned",
    description: "Monthly company-wide all-hands with CEO and CDO updates.",
  },
  {
    id: "ec-intranet-q2-refresh",
    title: "Intranet Q2 Refresh",
    sourceTracker: "Employee Comms Channel Tracker",
    sourceType: "Channel Activity",
    owner: "Cat",
    tags: ["Intranet"],
    startDate: "2026-04-23",
    allDay: true,
    location: "Intranet",
    status: "in-production",
    description: "Quarterly homepage refresh with new priorities, recognition, and resources.",
  },

  // ── 2025 Key Event Calendar ───────────────────────────────────────────────
  {
    id: "key-nailba",
    title: "NAILBA Annual Meeting",
    sourceTracker: "2025 Key Event Calendar",
    sourceType: "Event",
    owner: "Ashton Payne",
    tags: ["NAILBA", "Industry"],
    startDate: "2026-11-16",
    endDate: "2026-11-18",
    allDay: true,
    location: "Dallas, TX",
    status: "planned",
    description: "Top life insurance brokerage association annual meeting; AmeriLife attends in force.",
  },
  {
    id: "key-lamp",
    title: "LAMP Conference",
    sourceTracker: "2025 Key Event Calendar",
    sourceType: "Event",
    owner: "Ashton Payne",
    tags: ["LAMP", "Industry"],
    startDate: "2026-04-27",
    endDate: "2026-04-29",
    allDay: true,
    location: "Nashville, TN",
    status: "planned",
    description: "Life insurance marketing & management premier conference.",
  },
  {
    id: "key-naifa",
    title: "NAIFA Congressional Conference",
    sourceTracker: "2025 Key Event Calendar",
    sourceType: "Event",
    owner: "Ashton Payne",
    tags: ["NAIFA", "Advocacy"],
    startDate: "2026-05-18",
    endDate: "2026-05-19",
    allDay: true,
    location: "Washington, DC",
    status: "planned",
    description: "Industry advocacy day on Capitol Hill.",
  },

  // ── Marketing Mentors Deliverables ────────────────────────────────────────
  {
    id: "mm-affiliate-brand-book",
    title: "Affiliate Brand Book (v2)",
    sourceTracker: "Marketing Mentors Deliverables",
    sourceType: "Content",
    owner: "David Belleville",
    tags: ["Brand", "Deliverable"],
    startDate: "2026-05-30",
    allDay: true,
    status: "in-production",
    description: "Second-edition brand book for affiliate agencies; includes updated recruiting video spec.",
  },
  {
    id: "mm-sales-enablement-deck",
    title: "Sales Enablement Master Deck",
    sourceTracker: "Marketing Mentors Deliverables",
    sourceType: "Content",
    owner: "David Belleville",
    tags: ["Sales", "Deck"],
    startDate: "2026-06-20",
    allDay: true,
    status: "planned",
    description: "Comprehensive master deck to equip Distribution leadership for carrier conversations.",
  },

  // ── Professor Leads Weekly Themes ─────────────────────────────────────────
  {
    id: "pl-theme-2026-w16",
    title: "Professor Leads Weekly Theme — Wk 16",
    sourceTracker: "Professor Leads",
    sourceType: "Weekly Theme",
    owner: "Bill D",
    tags: ["Professor Leads", "Weekly"],
    startDate: "2026-04-13",
    endDate: "2026-04-19",
    allDay: true,
    location: "professorleads.com",
    status: "completed",
    description: "Weekly editorial theme driving all Professor Leads content for this week.",
  },
  {
    id: "pl-theme-2026-w17",
    title: "Professor Leads Weekly Theme — Wk 17",
    sourceTracker: "Professor Leads",
    sourceType: "Weekly Theme",
    owner: "Bill D",
    tags: ["Professor Leads", "Weekly"],
    startDate: "2026-04-20",
    endDate: "2026-04-26",
    allDay: true,
    location: "professorleads.com",
    status: "in-production",
    description: "Weekly editorial theme driving all Professor Leads content for this week.",
  },
  {
    id: "pl-theme-2026-w18",
    title: "Professor Leads Weekly Theme — Wk 18",
    sourceTracker: "Professor Leads",
    sourceType: "Weekly Theme",
    owner: "Bill D",
    tags: ["Professor Leads", "Weekly"],
    startDate: "2026-04-27",
    endDate: "2026-05-03",
    allDay: true,
    location: "professorleads.com",
    status: "planned",
    description: "Weekly editorial theme driving all Professor Leads content for this week.",
  },
];
